# universal minimalist fuzzel application launcher layout

[main]
font=lxgw wenkai mono:size=12
dpi-aware=yes
icon-theme=hicolor
show-actions=no
terminal=kitty
prompt="› "
layer=top
anchor=center

# geometric balancing lines
width=30
tabs=4
horizontal-pad=20
vertical-pad=15
inner-pad=10
image-size-ratio=0.5

line-height=24
fields=filename,name,generic

[border]
width=2
radius=8

[dmenu]
mode=text
exit-immediately-if-empty=no
