# universal monitor detection (0% rice - standard raw pipeline)
monitor=,preferred,auto,1

# core session autostart (triggering quickshell initialization)
exec-once = quickshell

# modifier keys and fundamental navigation keybinds
$mainMod = SUPER

bind = $mainMod, Return, exec, kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, M, exit, 
bind = $mainMod, V, togglefloating, 
bind = $mainMod, R, exec, wofi --show drun || rofi -show drun
